language: python
python:
  - "2.7"
notifications:
    email: false 
script: 
    - cd tests
    - nosetests test_featextract.py test_run.py test_input_output.py -v -s

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
      # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm 
      # Some Brian Magic to install libsamplerate
    - conda config --set always_yes yes --set changeps1 no
    - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $deps 
    - source activate test-environment
    - apt-get source libsamplerate
    - pushd libsamplerate-*
    - ./configure --prefix=$HOME/miniconda/envs/test-environment
    - make && make install
    - popd

install:
    # install gcc-4.8 with c++11 support: https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install ffmpeg # ffmpeg is in the default repo again. Duuuhhhh
    - sudo apt-get install g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    - sudo apt-get install liblapack-dev
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels cvxopt scikit-learn
    - conda install --yes -c dan_blanchard python-coveralls nose-cov 
    - git clone https://github.com/bmcfee/librosa.git
    - cd librosa
    - git checkout develop
    - python setup.py install
    - cd ..
    - python setup.py build
    - python setup.py install
